# Equal-Weight S&P 500 Index Fund

## Introduction & Library Imports

The S&P 500 is the world's most popular stock market index. The largest fund that is benchmarked to this index is the SPDR® S&P 500® ETF Trust. It has more than US$250 billion of assets under management.

The goal of this section of the course is to create a Python script that will accept the value of your portfolio and tell you how many shares of each S&P 500 constituent you should purchase to get an equal-weight version of the index fund.

## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
import numpy as np
import pandas as pd
import requests
import xlsxwriter
import math

## Importing Our List of Stocks

The next thing we need to do is import the constituents of the S&P 500.

These constituents change over time, so in an ideal world you would connect directly to the index provider (Standard & Poor's) and pull their real-time constituents on a regular basis.

Paying for access to the index provider's API is outside of the scope of this course. 

There's a static version of the S&P 500 constituents available here. [Click this link to download them now](https://drive.google.com/file/d/1ZJSpbY69DVckVZlO9cC6KkgfSufybcHN/view?usp=sharing). Move this file into the `starter-files` folder so it can be accessed by other files in that directory.

Now it's time to import these stocks to our Jupyter Notebook file.

In [2]:
stocks = pd.read_csv('sp_500_stocks.csv')
stocks.head(50)

   Ticker
0       A
1     AAL
2     AAP
3    AAPL
4    ABBV
5     ABC
6    ABMD
7     ABT
8     ACN
9    ADBE
10    ADI
11    ADM
12    ADP
13   ADSK
14    AEE
15    AEP
16    AES
17    AFL
18    AIG
19    AIV
20    AIZ
21    AJG
22   AKAM
23    ALB
24   ALGN
25    ALK
26    ALL
27   ALLE
28   ALXN
29   AMAT
30   AMCR
31    AMD
32    AME
33   AMGN
34    AMP
35    AMT
36   AMZN
37   ANET
38   ANSS
39   ANTM
40    AON
41    AOS
42    APA
43    APD
44    APH
45   APTV
46    ARE
47    ATO
48   ATVI
49    AVB

## Acquiring an API Token

Now it's time to import our IEX Cloud API token. This is the data provider that we will be using throughout this course.

API tokens (and other sensitive information) should be stored in a `secrets.py` file that doesn't get pushed to your local Git repository. We'll be using a sandbox API token in this course, which means that the data we'll use is randomly-generated and (more importantly) has no cost associated with it.

[Click here](http://nickmccullum.com/algorithmic-trading-python/secrets.py) to download your `secrets.py` file. Move the file into the same directory as this Jupyter Notebook before proceeding.

In [3]:
from secrets import IEX_CLOUD_API_TOKEN

## Making Our First API Call

Now it's time to structure our API calls to IEX cloud. 

We need the following information from the API:

* Market capitalization for each stock
* Price of each stock

In [12]:
symbol = 'AAPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/quote/?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()
print(data.keys())

dict_keys(['symbol', 'companyName', 'primaryExchange', 'calculationPrice', 'open', 'openTime', 'openSource', 'close', 'closeTime', 'closeSource', 'high', 'highTime', 'highSource', 'low', 'lowTime', 'lowSource', 'latestPrice', 'latestSource', 'latestTime', 'latestUpdate', 'latestVolume', 'iexRealtimePrice', 'iexRealtimeSize', 'iexLastUpdated', 'delayedPrice', 'delayedPriceTime', 'oddLotDelayedPrice', 'oddLotDelayedPriceTime', 'extendedPrice', 'extendedChange', 'extendedChangePercent', 'extendedPriceTime', 'previousClose', 'previousVolume', 'change', 'changePercent', 'volume', 'iexMarketPercent', 'iexVolume', 'avgTotalVolume', 'iexBidPrice', 'iexBidSize', 'iexAskPrice', 'iexAskSize', 'iexOpen', 'iexOpenTime', 'iexClose', 'iexCloseTime', 'marketCap', 'peRatio', 'week52High', 'week52Low', 'ytdChange', 'lastTradeTime', 'isUSMarketOpen'])

## Parsing Our API Call

The API call that we executed in the last code block contains all of the information required to build our equal-weight S&P 500 strategy. 

With that said, the data isn't in a proper format yet. We need to parse it first.

In [14]:
price = data['latestPrice']
market_cap = data['marketCap']

## Adding Our Stocks Data to a Pandas DataFrame

The next thing we need to do is add our stock's price and market capitalization to a pandas DataFrame. Think of a DataFrame like the Python version of a spreadsheet. It stores tabular data.

In [15]:
my_columns = ['Ticker', 'Stock Price', 'Market Capitalization', 'Number of Shares to buy']
final_df = pd.DataFrame(columns = my_columns)
final_df

Empty DataFrame
Columns: [Ticker, Stock Price, Market Capitalization, Number of Shares to buy]
Index: []

In [20]:
final_df.append(
    pd.Series(
    [
        symbol,
        price,
        market_cap,
        'N/A'
    ]
    ,index=my_columns),
        ignore_index=True
)

  Ticker  Stock Price Market Capitalization Number of Shares to buy
0   AAPL        133.1         2299195780074                     N/A

## Looping Through The Tickers in Our List of Stocks

Using the same logic that we outlined above, we can pull data for all S&P 500 stocks and store their data in the DataFrame using a `for` loop.

In [22]:
final_df = pd.DataFrame(columns=my_columns)
for stock in stocks['Ticker'][:10]:
    api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/quote/?token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(api_url).json()
    final_df = final_df.append(
    pd.Series(
    [
        stock,
        data['latestPrice'],
        data['marketCap'],
        'N/A'
    ],
    index=my_columns
    ),
        ignore_index=True
    )

In [23]:
final_df

  Ticker  Stock Price Market Capitalization Number of Shares to buy
0      A       135.95         2247472609049                     N/A
1    AAL       135.17         2306899060350                     N/A
2    AAP       134.22         2220123537927                     N/A
3   AAPL       138.20         2230272521907                     N/A
4   ABBV       136.35         2318501574641                     N/A
5    ABC       132.93         2325225289687                     N/A
6   ABMD       136.81         2323192481786                     N/A
7    ABT       137.26         2313375186508                     N/A
8    ACN       136.36         2265660345349                     N/A
9   ADBE       136.42         2317010706725                     N/A

## Using Batch API Calls to Improve Performance

Batch API calls are one of the easiest ways to improve the performance of your code.

This is because HTTP requests are typically one of the slowest components of a script.

Also, API providers will often give you discounted rates for using batch API calls since they are easier for the API provider to respond to.

IEX Cloud limits their batch API calls to 100 tickers per request. Still, this reduces the number of API calls we'll make in this section from 500 to 5 - huge improvement! In this section, we'll split our list of stocks into groups of 100 and then make a batch API call for each group.

In [24]:
def chunks(lst, n):
    'Yield successive n-sized chinks from lst.'
    for i in range(0, len(lst), n):
        yield lst[i:i+n]

In [40]:
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#    print(symbol_strings[i])
final_df = pd.DataFrame(columns=my_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=quote&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        final_df = final_df.append(
        pd.Series(
        [
            symbol,
            data[symbol]['quote']['latestPrice'],
            data[symbol]['quote']['marketCap'],
            'N/A'
        ], index=my_columns
        ),
        ignore_index=True)
final_df

    Ticker  Stock Price Market Capitalization Number of Shares to buy
0        A       125.53           38392026339                     N/A
1      AAL        18.01           10653977810                     N/A
2      AAP       154.23           10265742547                     N/A
3     AAPL       133.89         2275647701834                     N/A
4     ABBV       105.23          187284065580                     N/A
5      ABC       107.40           21594959833                     N/A
6     ABMD       352.07           16517335636                     N/A
7      ABT       125.20          224152443706                     N/A
8      ACN       243.35          160942549886                     N/A
9     ADBE       479.01          227371122059                     N/A
10     ADI       153.80           54540534180                     N/A
11     ADM        52.08           28504689511                     N/A
12     ADP       168.51           72530090986                     N/A
13    ADSK       278.91           61512822900                     N/A
14     AEE        75.59           18558874128                     N/A
15     AEP        82.26           41271596141                     N/A
16     AES        24.70           17017976098                     N/A
17     AFL        46.89           32913710848                     N/A
18     AIG        37.85           32261762799                     N/A
19     AIV         4.75             739056838                     N/A
20     AIZ       137.76            7999037161                     N/A
21     AJG       115.48           23067038638                     N/A
22    AKAM       115.74           18365406167                     N/A
23     ALB       168.40           17655864850                     N/A
24    ALGN       525.56           43386883637                     N/A
25     ALK        49.03            6096807405                     N/A
26     ALL       107.77           33513612823                     N/A
27    ALLE       107.42           10214085367                     N/A
28    ALXN       157.50           34869583246                     N/A
29    AMAT        99.24           89130088647                     N/A
..     ...          ...                   ...                     ...
475     VZ        55.60          229921030426                     N/A
476    WAB        76.94           14494545681                     N/A
477    WAT       275.06           17104490669                     N/A
478    WBA        52.59           44314837861                     N/A
479    WDC        58.91           17198426789                     N/A
480    WEC        91.30           28883105022                     N/A
481   WELL        60.90           26350084565                     N/A
482    WFC        31.34          128795454866                     N/A
483    WHR       192.62           12028488162                     N/A
484   WLTW       211.01           26328602256                     N/A
485     WM       116.69           48868846666                     N/A
486    WMB        22.24           26590721195                     N/A
487    WMT       142.80          416321913608                     N/A
488    WRB        63.77           11211031247                     N/A
489    WRK        42.60           10928708220                     N/A
490    WST       302.23           22146650776                     N/A
491     WU        22.64            9544416567                     N/A
492     WY        32.23           24228405357                     N/A
493   WYNN       100.35           10819795611                     N/A
494    XEL        65.37           33741539372                     N/A
495   XLNX       132.66           32319907912                     N/A
496    XOM        46.89          194034798051                     N/A
497   XRAY        53.91           12016227974                     N/A
498    XRX        21.78            4219673920                     N/A
499    XYL        97.31           18007381466                     N/A
500    YUM       105.62           31310253850                     N/A
501    ZBH       154.24           32532246180                     N/A
502   ZBRA       394.90           21654725482                     N/A
503   ZION        44.25            7344567204                     N/A
504    ZTS       157.12           75475371859                     N/A

[505 rows x 4 columns]

## Calculating the Number of Shares to Buy

As you can see in the DataFrame above, we stil haven't calculated the number of shares of each stock to buy.

We'll do that next.

In [49]:
portfolio_size = input('Enter the value of your portfolio:')

try:
    val = float(portfolio_size)
except ValueError:
    print("That's not a number!\nPlease try again:")
    portfolio_size = input('Enter the value of your portfolio:')
    val = float(portfolio_size)

Enter the value of your portfolio:10000000

In [51]:
position_size

0.0019801980198019802

In [52]:
position_size = val/len(final_df.index)
for i in range(0, len(final_df.index)):
    final_df.loc[i, 'Number of Shares to buy'] = math.floor(position_size/final_df.loc[i, 'Stock Price'])

final_df

    Ticker  Stock Price Market Capitalization  Number of Shares to buy
0        A       125.53           38392026339                      157
1      AAL        18.01           10653977810                     1099
2      AAP       154.23           10265742547                      128
3     AAPL       133.89         2275647701834                      147
4     ABBV       105.23          187284065580                      188
5      ABC       107.40           21594959833                      184
6     ABMD       352.07           16517335636                       56
7      ABT       125.20          224152443706                      158
8      ACN       243.35          160942549886                       81
9     ADBE       479.01          227371122059                       41
10     ADI       153.80           54540534180                      128
11     ADM        52.08           28504689511                      380
12     ADP       168.51           72530090986                      117
13    ADSK       278.91           61512822900                       70
14     AEE        75.59           18558874128                      261
15     AEP        82.26           41271596141                      240
16     AES        24.70           17017976098                      801
17     AFL        46.89           32913710848                      422
18     AIG        37.85           32261762799                      523
19     AIV         4.75             739056838                     4168
20     AIZ       137.76            7999037161                      143
21     AJG       115.48           23067038638                      171
22    AKAM       115.74           18365406167                      171
23     ALB       168.40           17655864850                      117
24    ALGN       525.56           43386883637                       37
25     ALK        49.03            6096807405                      403
26     ALL       107.77           33513612823                      183
27    ALLE       107.42           10214085367                      184
28    ALXN       157.50           34869583246                      125
29    AMAT        99.24           89130088647                      199
..     ...          ...                   ...                      ...
475     VZ        55.60          229921030426                      356
476    WAB        76.94           14494545681                      257
477    WAT       275.06           17104490669                       71
478    WBA        52.59           44314837861                      376
479    WDC        58.91           17198426789                      336
480    WEC        91.30           28883105022                      216
481   WELL        60.90           26350084565                      325
482    WFC        31.34          128795454866                      631
483    WHR       192.62           12028488162                      102
484   WLTW       211.01           26328602256                       93
485     WM       116.69           48868846666                      169
486    WMB        22.24           26590721195                      890
487    WMT       142.80          416321913608                      138
488    WRB        63.77           11211031247                      310
489    WRK        42.60           10928708220                      464
490    WST       302.23           22146650776                       65
491     WU        22.64            9544416567                      874
492     WY        32.23           24228405357                      614
493   WYNN       100.35           10819795611                      197
494    XEL        65.37           33741539372                      302
495   XLNX       132.66           32319907912                      149
496    XOM        46.89          194034798051                      422
497   XRAY        53.91           12016227974                      367
498    XRX        21.78            4219673920                      909
499    XYL        97.31           18007381466                      203
500    YUM       105.62           31310253850                      187
501    ZBH       154.24           32532246180                      128
502   ZBRA       394.90           21654725482                       50
503   ZION        44.25            7344567204                      447
504    ZTS       157.12           75475371859                      126

[505 rows x 4 columns]

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

### Initializing our XlsxWriter Object

In [88]:
writer = pd.ExcelWriter('recommended trades.xlsx', engine = 'xlsxwriter')
final_df.to_excel(writer, 'Recommended Trades', index=False)

### Creating the Formats We'll Need For Our `.xlsx` File

Formats include colors, fonts, and also symbols like `%` and `$`. We'll need four main formats for our Excel document:
* String format for tickers
* \\$XX.XX format for stock prices
* \\$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

In [89]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_format = writer.book.add_format(
    {
    'font_color': font_color,
        'bg_color': background_color,
        'border': 1
    }
)

dollar_format = writer.book.add_format(
    {
        'num_format': '$0.00',
    'font_color': font_color,
        'bg_color': background_color,
        'border': 1
    }
)

integer_format = writer.book.add_format(
    {'num_format': '0',
    'font_color': font_color,
        'bg_color': background_color,
        'border': 1
    }
)

### Applying the Formats to the Columns of Our `.xlsx` File

We can use the `set_column` method applied to the `writer.sheets['Recommended Trades']` object to apply formats to specific columns of our spreadsheets.

Here's an example:

```python
writer.sheets['Recommended Trades'].set_column('B:B', #This tells the method to apply the format to column B
                     18, #This tells the method to apply a column width of 18 pixels
                     string_template #This applies the format 'string_template' to the column
                    )
```

In [90]:
#writer.sheets['Recommended Trades'].set_column('A:A', 18, string_format)
#writer.sheets['Recommended Trades'].set_column('B:B', 18, string_format)
#writer.sheets['Recommended Trades'].set_column('C:C', 18, string_format)
#writer.sheets['Recommended Trades'].set_column('D:D', 18, string_format)
#writer.save()

#writer.sheets['Recommended Trades'].write('A1', 'Ticker', string_format)
#writer.sheets['Recommended Trades'].write('B1', 'Stock Price', dollar_format)
#writer.sheets['Recommended Trades'].write('C1', 'Market Capitalization', dollar_format)
#writer.sheets['Recommended Trades'].write('D1', 'Number of Shares to buy', integer_format)

This code works, but it violates the software principle of "Don't Repeat Yourself". 

Let's simplify this by putting it in 2 loops:

In [91]:
column_formats = {
    'A': ['Ticker', string_format],
    'B': ['Stock Price', dollar_format],
    'C': ['Market Capitalization', dollar_format],
    'D': ['Number of Shares to buy', integer_format]
}

for column in column_formats.keys():
    writer.sheets['Recommended Trades'].set_column(f'{column}:{column}', 18, column_formats[column][1])
    writer.sheets['Recommended Trades'].write(f'{column}1', column_formats[column][0], column_formats[column][1])

## Saving Our Excel Output

Saving our Excel file is very easy:

In [ ]:
writer.save()